name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y make gcc

    - name: Build project
      run: make

    - name: Run tests
      run: |
        make test
        echo "Checking test results..."
        if ! grep -q "All tests passed successfully" <<< "$(cat test.out)"; then
          echo "Tests failed or not all tests passed."
          exit 1
        fi
        echo "All tests passed as expected!"

    - name: Clean up
      run: make fclean

